// Generated by CoffeeScript 2.2.4
var Bananas;

import React, {
  Component
} from 'react';

import {
  Image
} from 'react-native';

Bananas = class Bananas extends Component {
  render() {
    var pic;
    pic = {
      uri: 'https://upload.wikimedia.org/wikipedia/commons/d/de/Bananavarieties.jpg'
    };
    return <Image source={pic} style={{
        width: 193,
        height: 110
      }} />;
  }

};

module.exports = Bananas;
