// Generated by CoffeeScript 2.2.4
var App, Greeting;

import React, {
  Component
} from 'react';

import {
  Text,
  View
} from 'react-native';

Greeting = class Greeting extends Component {
  constructor(props) {
    super(props);
    this.state = {
      is_showing_text: true
    };
    setInterval(() => {
      return this.setState((previousState) => {
        return {
          is_showing_text: !previousState.is_showing_text
        };
      });
    }, 1000);
  }

  render() {
    var text;
    text = this.state.is_showing_text ? this.props.name : ' ';
    return <Text>{text}</Text>;
  }

};

module.exports = App = class App extends Component {
  render() {
    return <View style={{
        flex: 1
      }}>
      <View style={{
        flex: 1,
        backgroundColor: 'powderblue'
      }} />
      <View style={{
        flex: 2,
        backgroundColor: 'skyblue'
      }} />
      <View style={{
        flex: 3,
        backgroundColor: 'steelblue',
        alignItems: 'center'
      }}>
        <Greeting name='Rexxar' />
        <Greeting name='Jaina' />
        <Greeting name='Valeera2' />
        <Text>wtf</Text>
      </View>
    </View>;
  }

};
