// Generated by CoffeeScript 2.2.4
var App, Greeting;

import React, {
  Component
} from 'react';

import {
  Text,
  View,
  TextInput,
  Button,
  Alert
} from 'react-native';

Greeting = class Greeting extends Component {
  constructor(props) {
    super(props);
    this.state = {
      is_showing_text: true
    };
    setInterval(() => {
      return this.setState((previousState) => {
        return {
          is_showing_text: !previousState.is_showing_text
        };
      });
    }, 1000);
  }

  render() {
    var text;
    text = this.state.is_showing_text ? this.props.name : ' ';
    return <Text>{text}</Text>;
  }

};

module.exports = App = class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      text: ''
    };
  }

  render() {
    return <View style={{
        flex: 1
      }}>
      <View style={{
        flex: 1,
        backgroundColor: 'powderblue'
      }}>
        <TextInput style={{
        height: 40
      }} placeholder='Type something here' onChangeText={(text) => {
        return this.setState({
          text: text
        });
      }} />
      </View>
      <View style={{
        flex: 2,
        backgroundColor: 'skyblue'
      }}>
        <Text style={{
        padding: 10,
        fontSize: 42
      }}>
          {this.state.text.split('').reverse().join('')}
        </Text>
        <Button onPress={() => {
        return Alert.alert('You tapped the button.');
      }} title="Press me" />
      </View>
      <View style={{
        flex: 2,
        backgroundColor: 'steelblue',
        alignItems: 'center'
      }}>
        <Greeting name='Rexxar' />
        <Greeting name='Jaina' />
        <Greeting name='Valeera2' />
        <Text>wtf</Text>
      </View>
    </View>;
  }

};
